//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFlightDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FlightsDBContext : DbContext
    {
        public FlightsDBContext()
            : base("name=FlightsDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airline> Airlines { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
    
        public virtual int uspUpdateFilghtPrice(Nullable<int> airlinesID, Nullable<double> price, Nullable<System.DateTime> traveldate)
        {
            var airlinesIDParameter = airlinesID.HasValue ?
                new ObjectParameter("AirlinesID", airlinesID) :
                new ObjectParameter("AirlinesID", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(double));
    
            var traveldateParameter = traveldate.HasValue ?
                new ObjectParameter("traveldate", traveldate) :
                new ObjectParameter("traveldate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateFilghtPrice", airlinesIDParameter, priceParameter, traveldateParameter);
        }
    }
}
