//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFlightDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public Nullable<int> AirlinesID { get; set; }
        public string SourceCity { get; set; }
        public string Destination { get; set; }
        public System.DateTime TravelDate { get; set; }
        public double Price { get; set; }
        public string TravelTime { get; set; }
    
        public virtual Airline Airline { get; set; }
    }
}
